name: memory_game
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/bear.png
    - assets/img/cow.png
    - assets/img/fox.png
    - assets/img/jackal.png
    - assets/img/lion.png
    - assets/img/monkey.png
    - assets/img/panda.png
    - assets/img/parrot.png
    - assets/img/pig.png
    - assets/img/sheep.png
